spring:
  application:
    name: UserService
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:liquibase/changelog/master.yaml

openapi:
  oauth:
    issuer-uri: ${OAUTH_ISSUER_URI}

cache:
  ttl:
    default: 10m
    user: 1h
    userCards: 1h
    userByEmail: 1h
    users: 5m
    card: 30m
    cards: 10m

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    com.intern.userservice.service: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  otlp:
    metrics:
      export:
        url: "http://localhost:4318/v1/metrics"
    logging:
      export:
        enabled: true
      endpoint: "http://localhost:4318/v1/logs"
    tracing:
      export:
        enabled: true
      endpoint: "http://localhost:4318/v1/traces"
  observations:
    key-values:
      application: ${spring.application.name}