spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: test

logging:
  level:
    root: info
