spring:
  application:
    name: UserService

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:liquibase/changelog/master.yaml

cache:
  ttl:
    default: 10m
    user: 1h
    userCards: 1h
    userByEmail: 1h
    users: 5m
    card: 30m
    cards: 10m

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
