name: CI - build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

#      - name: Cache Gradle (placeholder)
#        if: false
#        run: echo "no-op"
#
#      - name: Cache Docker buildx (for later docker cache)
#        uses: actions/cache@v4
#        with:
#          path: ~/.cache/docker
#          key: ${{ runner.os }}-docker-cache-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-docker-cache-
#
#      - name: Cache Maven repository
#        uses: actions/cache@v4
#        with:
#          path: ~/.m2/repository
#          key: maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: maven-
#
#      - name: Set up QEMU and Docker Buildx
#        uses: docker/setup-buildx-action@v2

      - name: Install mvnw executable
        run: chmod +x ./mvnw

      - name: Run Unit Tests
        run: ./mvnw -B test -Dgroups=unit

      - name: Run Integration Tests and SonarQubeScan
        run: |
          ./mvnw -B verify -Dgroups=integration \
            sonar:sonar \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.organization=${SONAR_ORGANIZATION} \
            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
            -Dsonar.token=${SONAR_TOKEN}

      - name: Package application
        run: ./mvnw -B -DskipTests package

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
