name: CI - build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Install mvnw executable
        run: chmod +x ./mvnw

      - name: Run Unit Tests
        run: ./mvnw -B test -Dgroups=unit

  integration-tests:
    name: Integration Tests + SonarQube
    runs-on: ubuntu-latest
    needs: unit-tests
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Install mvnw executable
        run: chmod +x ./mvnw

      - name: Run Integration Tests and SonarQube Scan
        run: |
          ./mvnw -B verify -Dgroups=integration -DskipUnitTests=true \
            sonar:sonar \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.organization=${SONAR_ORGANIZATION} \
            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
            -Dsonar.login=${SONAR_TOKEN}